### ISSUE TITLE
ADM - support from BSP for the 1.21 deployment on 02/08 @16:30

### ISSUE THREAD

**Issue by sghumphreys** [UKHomeOffice/application-container-platform#418]
I am raising this ticket for a named resource to provide remote support to the ADM release deployment on 02/08/17 @16:30 - 17:30. Jay Keshur usually provides this support, but Jay is on leave this week. In the past when Jay has been on leave - we have had Joe Irving join our ADM skype group.  We would want someone to join our skype group, should we have any infrastructure problems that need support from DSP to resolve. Thanks, Simon Humphreys

**Comment by AwkwardBen** [comment]
So as discussed in the email it is better to add this to the bau board (https://github.com/UKHomeOffice/application-container-platform-bau). We can look at it there.

**Comment by sghumphreys** [comment]
Hi – for that link, I get this:

[cid:image001.png@01D30AB1.2BA29200]

Regards,
Simon Humphreys
Release Management
Immigration IT Portfolio
Home Office Digital, Data and Technology
1st Floor Metro Point
Croydon CR0 2EU
MOBILE NUMBER: 0789 453 9947

**Comment by sghumphreys** [comment]
Hi I get a 404 error when trying to access https://github.com/UKHomeOffice/application-container-platform-bau

**Comment by AwkwardBen** [comment]
Ok so I'll need to add your full name and email to your github profile. If also do you have 2 factor auth setup?

**Comment by sghumphreys** [comment]
Thanks Ben - the deployment is tomorrow (weds) at 16:30. Could you give me your skype username so I can add you to the skype group?
