### ISSUE TITLE
Addign Arunkumar to Gitlab UKHomeOffice organisation

### ISSUE THREAD

**Issue by ranjithmurugan-ho** [UKHomeOffice/application-container-platform#437]
HI,

Could we add (arun-go) arunkumar.gopalan@homeoffice.gsi.gov.uk from the BX Architecture team  to UKHomeOffice organisation.

Regards,
Ranjith

**Comment by jaykeshur** [comment]
please add this to https://github.com/UKHomeOffice/application-container-platform-bau, not here.
