### ISSUE TITLE
Sysdig Bug: Alerts not triggering for pods restart

### ISSUE THREAD

**Issue by amriaz** [UKHomeOffice/application-container-platform#479]
I raise this as a bug as we are not finding that are pod restarts are triggering alerts. This is blocking OAT and is of high priority for the AUK AWS migration plan. 
Alerts are configured correctly, in a manner matching IPT-PRP1 and yet they are not triggering - when we go into alerts there are none showing for the criteria that has been matched.
This is not about emails or notifications to slack not being sent, the sysdig UI is registering correctly the alerts even when the dashboard shows the criteria have been met.
AUK: Dummy Alert is what we have been using to test this alert functionality.
https://sysdighod.service.ops.iptho.co.uk/#/fast-dashboards/658/l:600 is the dashboard that shows our target pod: customer that is registering that it has been restarted
 
These restart numbers match the criteria of the alert but the alerts are not triggering.
It is suggested raising this with sysdig support with the above information and the contact detail below: 
Sysdig team: IPT
Sysdig SaaS URL: https://sysdig.homeofficedigital.homeoffice.gsi.gov.uk
Home Office - UK Government
London
Account contacts: Jonathan Shanks, Jay Shakur

**Comment by tasharnvb** [comment]
Hi, please re-create this ticket on the [application container platform bau board](https://github.com/UKHomeOffice/application-container-platform-bau/issues).
