### ISSUE TITLE
This is a request to create new AWS users

### ISSUE THREAD

**Issue by horrella** [UKHomeOffice/application-container-platform#490]
This is a request to create new AWS users (adam.horrell@homeoffice.gsi.gov.uk) with delegated admin access on the following CTI accounts.
Below is a link to obtain the users public PGP key for auth encryption
https://keybase.io/horrella/
They will need to be granted the same access as jack.jarrett@homeoffice.gsi.gov.uk and in doing so, be able to access the following 2 accounts:
076130172497 (Prod)
124538368460 (Dev)
via:
https://signin.aws.amazon.com/switchrole?account=076130172497&roleName=restricted_admin&displayName=idp-prod_admin
https://signin.aws.amazon.com/switchrole?account=124538368460&roleName=restricted_admin&displayName=idp-npa_admin

**Comment by tasharnvb** [comment]
Hi, please re-create this ticket on the [application container platform bau board](https://github.com/UKHomeOffice/application-container-platform-bau/issues).

Also, you will approval for access to the prod account so when you re-create the ticket please get your team leader to leave a comment approving your request.
