### ISSUE TITLE
Authorized User

### ISSUE THREAD

**Issue by martinjordan5** [UKHomeOffice/application-container-platform#496]
Hello All. I am authorized to work from home using my EUD. However, I can not get the verification code to get to the VPN portal. I noticed that the number on my account is incorrect (the number ends in 96) my current number is (07507 555 025). My questions are two fold:

1. Can I please have my mobile number updated on my account martin.jordan@digital.homeoffice.gov.uk"?

2. Am I going about establishing my VPN connection to the BX AWS platform by accessing "access-acp"? If I am using the wrong method can you please advise me where I am going wrong?

Thanks.
Mj

**Comment by jaykeshur** [comment]
Hi,

1. This should have been raised on the bau board: https://github.com/UKHomeOffice/application-container-platform-bau
2. We do not manage Office 365, so will be unable to help you there.
3. Yes, the HODC-preprod and prod profiles on the access-acp page.

Cheers.
