### ISSUE TITLE
Cannot connect to Jenkins CLI

### ISSUE THREAD

**Issue by vjpujar** [UKHomeOffice/application-container-platform#519]
Trying to connect to Jenkins CLI using:
java -jar jenkins-cli.jar -s https://formsso-jenkins.ci.acp.homeoffice.gov.uk/

This is failing with an error:
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

Requirement:
Need access to the Jenkins CLI to be able to install PhantomJS, Ruby, Capybara to be able to run the automated tests on the legacy services
Also need to install the bundlers package manager and rvm to switch between ruby versions

**Comment by jaykeshur** [comment]
This should be raised on the application-container-platform-bau repo, not here.
But to address your issue - you should be running in containers. Also, your team is responsible for Jenkins and we do not provide assistance on an unsupported service, we've simply given you a pattern to host it on ACP.

**Comment by oyelekci** [comment]
@vjpujar The new SO instance is at https://formsso-jenkins.ci.acp.homeoffice.gov.uk btw
cc. @JoeChapman
