### ISSUE TITLE
Readonly access to abc-connectivity AWS account

### ISSUE THREAD

**Issue by A-Gordon** [UKHomeOffice/application-container-platform#521]
Could you please grant me access to assume the readonly role on the abc-connectivity account? 

IAM User:
andrew.gordon6@homeoffice.gsi.gov.uk

**Comment by anoother** [comment]
This should be raised on application-container-platform-bau, not here.

The account in question is ABC prod -- 0777-2425-5962

**Comment by A-Gordon** [comment]
Oops, I'll raise another one in the correct place. 

Thanks.
