### ISSUE TITLE
AWS console access request

### ISSUE THREAD

**Issue by benoliver91** [UKHomeOffice/application-container-platform#540]
This is a request to create new AWS users benjamin.oliver@homeoffice.gsi.gov.uk with delegated admin access on the following CTI accounts.
Below is a link to obtain the users public PGP key for auth encryption
https://keybase.io/benoliver/
They will need to be granted the same access as jack.jarrett@homeoffice.gsi.gov.uk and in doing so, be able to access the following 2 accounts:
076130172497 (Prod)
124538368460 (Dev)
via:
https://signin.aws.amazon.com/switchrole?account=076130172497&roleName=restricted_admin&displayName=idp-prod_admin
https://signin.aws.amazon.com/switchrole?account=124538368460&roleName=restricted_admin&displayName=idp-npa_admin

**Comment by benoliver91** [comment]
@DebraSheppard please approve this request

**Comment by tasharnvb** [comment]
Hi, this is a request that should be on the bau board here: https://github.com/UKHomeOffice/application-container-platform-bau/
