### ISSUE TITLE
HOPS access for Edward Croucher (L2 Application Technician)

### ISSUE THREAD

**Issue by crouchee** [UKHomeOffice/application-container-platform#541]
This is a request to create new AWS users (edward.croucher@homeoffice.gsi.gov.uk) with delegated admin access on the following CTI accounts.
Below is a link to obtain the users public PGP key for auth encryption
https://keybase.io/edwardcroucher
They will need to be granted the same access as jack.jarrett@homeoffice.gsi.gov.uk and in doing so, be able to access the following 2 accounts:
076130172497 (Prod)
124538368460 (Dev)
via:
https://signin.aws.amazon.com/switchrole?account=076130172497&roleName=restricted_admin&displayName=idp-prod_admin
https://signin.aws.amazon.com/switchrole?account=124538368460&roleName=restricted_admin&displayName=idp-npa_admin

@DebraSheppard Can you please provide formal approval. :+1:

**Comment by tasharnvb** [comment]
Hi, this is a request that should be on the bau board: https://github.com/UKHomeOffice/application-container-platform-bau/

**Comment by DebraSheppard** [comment]
Approved

Debra

Regards
Debra Sheppard
TSS Service Manager (ELS & SA)
Home Office 
Metro Point
Croydon
Mobile: 07805 548675

Planned Out of Office: 
Vacation:
