### ISSUE TITLE
AWS write access into the Shared Data Platform (SDP)

### ISSUE THREAD

**Issue by collinsonk** [UKHomeOffice/application-container-platform#554]
Hi,
Can I have AWS access into the Shared Data Platform (SDP)? As part of our day to day work to perform as 2nd line / 3rd line support I would need write access to all the AWS components.
Please let us know if you require further information.
Thanks in advance.

**Comment by tasharnvb** [comment]
Hi, this is a request that should be raised on the bau board: https://github.com/UKHomeOffice/application-container-platform-bau/
