### ISSUE TITLE
Unable to set up an MFA device - edward.croucher@homeoffice.gsi.gov.uk

### ISSUE THREAD

**Issue by crouchee** [UKHomeOffice/application-container-platform#559]
I am able to get into the AWS console with the account, but unable to set up an MFA device to progress through the rest of the setup procedure, as I receive the following error:
![image](https://user-images.githubusercontent.com/34499208/40059158-3e82aa3e-584b-11e8-8337-7c2f04b85cc2.png)

Please can I be given the required access as part of the L2 TSS live support team.

**Comment by tasharnvb** [comment]
Hi, this is a request that should be raised on the bau board: https://github.com/UKHomeOffice/application-container-platform-bau/
