### ISSUE TITLE
New user

### ISSUE THREAD

**Issue by simongibbons1** [UKHomeOffice/application-container-platform#580]
This is a request to create new AWS users (simon.gibbons@homeoffice.gsi.gov.uk) with delegated admin access on the following CTI accounts.
Below is a link to obtain the users public PGP key for auth encryption
https://keybase.io/bloggsj/
They will need to be granted the same access as Alex.Light@homeoffice.gsi.gov.uk and in doing so, be able to access the following 2 accounts:
076130172497 (Prod)
124538368460 (Dev)
via:
https://signin.aws.amazon.com/switchrole?account=076130172497&roleName=restricted_admin&displayName=idp-prod_admin
https://signin.aws.amazon.com/switchrole?account=124538368460&roleName=restricted_admin&displayName=idp-npa_admin

**Comment by tasharnvb** [comment]
Hi, this is a request that should be raised on the bau board: https://github.com/UKHomeOffice/application-container-platform-bau/
