### ISSUE TITLE
Kube token for dsp prod cluster to access srrs-prod & srrs-ooph-prod namespaces for Nick Aldridge

### ISSUE THREAD

**Issue by NickAldridge** [UKHomeOffice/application-container-platform#599]
Hi,
Please may I have a kube token for accessing the rrs-prod & rrs-ooph-prod namespaces? Please send via nick.aldridge@homeoffice.gsi.gov.uk

-----BEGIN PGP PUBLIC KEY BLOCK-----

mQINBFtwqLsBEADHG6n2KWUQ49ybv4Nr0h5+VWxIwc/TLGB2DYDkX85iYBdQuhI0
mztnERXEshkJDZ3yXzchrdAP+3KKD2+bvuxSMIVg714E4JSo3H20PcogtRtsct/h
1zNeqOm2Nqr0JfeJ4jSG3h7hykplP7GvS2+NMewm9q5JSryM5O1Rjp/kdRxYk0e6
Xu0WG8oVPHNLzqjyVtlAjaVuNUdw19aRDzHVD/lyvWuSiIrXJ/QWU7dS7uDnOjbV
FWAeH3/yp97txweMpHTwmVn2mSTgg/8i5tGlnxkKxwm+emd3+GGJ99gninGnwodb
vuq3H+QXtI6Xp4JooZrPgY7GLAWpNwZAuj/bqP+wSfEdyf/d7Nmnv1+0dc6k+2op
7M6tb5PGpnB3v9yotObEkNjJMOj/f3b4RFFOHfBlwrmvyfwtxNKYNRXw+EK1ji/b
C7NJjrWlp3f8+e4H0FDJlWH5UM2/+3Pbff7Eqw+BBDdVa0YLWtPglF6I2nMyp/zu
9vLdCDthLgbNkxt2W+6as2zJ3/mDYdwbAXw3k4KTwj9unUqm25BxChPZPfjKe8bH
p7nUf/+aLgq5TNTMBkYTKGKY0fjIcv+3e5yLrfppEBPFyvDPA7k39qikccgR1Ui+
13muROAsQXJjmCHtFj7ckQHtTVJXbMx8p1t+dSNruHp4/PQ3bjLqpqIGZwARAQAB
tDNOaWNrIEFsZHJpZGdlIDxuaWNrLmFsZHJpZGdlQGhvbWVvZmZpY2UuZ3NpLmdv
di51az6JAjgEEwECACIFAltwqLsCGwMGCwkIBwMCBhUIAgkKCwQWAgMBAh4BAheA
AAoJEPhADNsjuSBxFoIP/19VuymIeT4az3Tt/BE5ySvkNgNMvefYVaUJ6P7Uv6qw
CzakdssIeA+Zp57sWFMKoHzvDzZhdvoPujxBfmLRQGDNY4ih7fjv0/fPST/xlJdw
PjURG8YfxEG26bztLMAhJM6bH3SRKjrPMVIiWII8mxrau+1ocFWt3DybRsXzoDZu
aCLB28SHgzi6aevNNlF/3+Nj6c8BRztIGfhsCloKSGNWnmtgkiwjxfz77iN0HF3U
ceZLCV/+PJ/QXdx2WB10A8DR4a15sOHIFt0XwhYAfDc5gmoLbB0EcKI/f4qAX63/
3espzG5mzb56xt0jxvuWsZ/XbMVq+r0t22Y/dMqRTe1sPMipYEO3cyv2Q1AJPSNB
dkpIR0gt5eMk+kyLR2EpAz131zxIsj4IQmb+HcEBs8l9HGZN2hqbtmpGfbahZs04
/y15/YZZbVrbcGsh87NKT44zNRgxto8UE/+27HVMfV4wN7sx/ufG+wR8x4SZzdbN
n/cNEwLRtPUv0DSRpJY/K4LAeZi7eFmbCEDbFLoIX56Kx053G5VpMr/wKo+pcSi3
/qSfoyzkSNjDCcrzuj/T89+GTLVbD/+dOUuvtA/aOl+Mno/neNQaUHmYcZwHFmL4
C8Fsjd0e3a2Qe5nrYgLrAsFRhbXJzN0NWcPipZdHHjn7klS6mVdvVLz9air2l1dK
uQINBFtwqLsBEAClgUj0fHbQMRi8pGBED+eLzmxTlpJYHLv3jtjE9QjAGLPpdXwd
zMS9peS0/oXYPCLD1EaQPN45JpFzRrb3hyT+iUrC5Bxd2fPsxkwoRG9FcJA4mTFI
FZw0axVhPWOR6JYq8xVj8sPpAUyJ2R8ls76HGTdgUw7icsiR5HuECc8ggPqkBRGV
73mvQsvIZD0tbBOLp22uSh4Ac1kx/2dzDPU01QRiCDjw271XswgpI6VKj5ocpKJi
VL+XH437TcQz4tPQG0QtCndJUkpUHb9VN954p9HCxz5EIGxniG6mMwRdqzKJuHCQ
qIqwcTlS7yzZqhOC3NZdww7G6M5NVR0U69XRqJA1mHYTk72hcpmiZs70yK8Ov4WQ
byBYXfNk9s4e7Lgbvl5j/X99gx8YrYPZWkD9tDpOcyjElmJjmoh5jHuVlXwBTN6v
sIEMpxok/8qlrTJ0FhY+c1cEa8LG1u7Kdd/aG8DxuQuRfZPV/t3mp4WWUz1vMeXu
iymjNAN1PCFNQXXa6QS1Oi/INc79Rd1BaxYU9Z/Zj+JkaDsBngoCGNGD2SuyNQ1T
K/t3Lgr9pbOlF3HOVj2mUAAFgQJlGaw7jCtqcXP0eQpOWoJJete9OeqFBIyin7r4
SQPW29LpK6B60DNIrrJLYyCO58HQxE/2H2CiJORpYl8zrxJ1LYM422M7TQARAQAB
iQIfBBgBAgAJBQJbcKi7AhsMAAoJEPhADNsjuSBxh9oQAIpPG4+F/Q3n9wxkw6b8
xYWdfXG9+ksviCGBgPniz8axUidsqpoVjqcLUgqCxxhoNSl/gZRtEFGSW2OMOqZ2
kVI6oUPjl2tMfI4rONHiQg3ynV9l8Y1oRauVyy3zK1H8Knu5zCub4CoHMTFBeMvH
5iSkQlogsNkC87xX7YHWVZRLyqBLcGfUitxiBU8tCIBbp9JkAJxCmdkpSVrwqGsl
htytkPI7TeRV51DSugabx+roekwR4fjMRpYMoB0gs0q2pAf2WLIyQDqmBtJDNgWa
zOBUP94adsYD6stjzNZghM0oYGxyGVl8RSI4EaAOnjQVitYuTcSocFCApf91W6G0
ZySyAK9yu45jTvGPF+000T1L6a2nUjbzSCU0oK8MesdtWjdWvFKWpL8Sr6R01Xh/
LTMCJN5tEOO818mE/WW+L7fqiT/3W3zo+szC1KM2wzXWZzMxjljMlsibxr4h8Xcr
nUl+sGAoxvyl9FW2qOqV4doLOOnQydrOOD6VuxDjOQwUmkZy3Q4vYqSy2GWp7/Pj
TDKq5bCI/b4XDs4SU0Hi0YFX3kKWnscR681iHx88qWcD6Hup0/1/Xax1W5q8xFi/
FNRXy5A3v9bidIO55CiIzPYLLUVrTiueRQl69uBUiMZx7x/ld9UST4Bh2vOCi91/
rWgiiWfZ2JuIUwgmGHly0jXS
=hJ9k
-----END PGP PUBLIC KEY BLOCK-----

Many thanks

**Comment by tasharnvb** [comment]
Hi, this is a request that should be raised on the bau board: https://github.com/UKHomeOffice/application-container-platform-bau/

**Comment by NickAldridge** [comment]
Hi I did raise this on the bau board and received this response,

ACP kube tokens are self-service. Please sign into https://hub.acp.homeoffice.gov.uk with O365 and ask SRRS project admins (Leszek Sliwko, Phil McLaughlin) to add you to their team.

**Comment by tasharnvb** [comment]
https://github.com/UKHomeOffice/application-container-platform/issues/600#issuecomment-423936249
