### ISSUE TITLE
Regarding #599 Kube token for dsp prod cluster to access srrs-prod & srrs-ooph-prod namespaces for Nick Aldridge

### ISSUE THREAD

**Issue by NickAldridge** [UKHomeOffice/application-container-platform#600]
Hi I did raise this on the bau board and received this response,

ACP kube tokens are self-service. Please sign into https://hub.acp.homeoffice.gov.uk with O365 and ask SRRS project admins (Leszek Sliwko, Phil McLaughlin) to add you to their team.

Please can you advise?

**Comment by tasharnvb** [comment]
Hi, this is correct for ACP, not DSP. You did not specify which you needed the token for so it was assumed you were talking about ACP. Please raise this request on the BAU board (or re-open the ticket that you originally opened).
