### ISSUE TITLE
4 accounts for Visor developers

### ISSUE THREAD

**Issue by kellysandhu** [UKHomeOffice/application-container-platform#604]
Hi,

I would like 4 accounts set up for the following people:

Nick Jaswal nick.jaswal@homeoffice.gov.uk
Raymond Chan Raymond.chan@homeoffice.gov.uk
Don Bradley don.bradley1@homeoffice.gov.uk
Simon Hunt simon.hunt2@homeoffice.gis.gov.uk 

The intention is for ViSOR to be migrated into AWS, the accounts will give the develops an opportunity to familiarise themselves with the new environment.

Please let me know if you require further information.

Kind regards
Kelly Sandhu

**Comment by oyelekci** [comment]
Closing this as this is not the BAU board and it's been dealt with under https://github.com/UKHomeOffice/application-container-platform-bau/issues/4329
